//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Artist defines model for Artist.
type Artist struct {
	// Id Artist slug or ID
	Id       string                  `json:"id"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Name Artist display name
	Name string `json:"name"`

	// Url Profile or TicketDive artist URL
	Url *string `json:"url,omitempty"`
}

// BatchEventResponse defines model for BatchEventResponse.
type BatchEventResponse struct {
	ApiVersion string             `json:"apiVersion"`
	Results    []BatchEventResult `json:"results"`
	Success    bool               `json:"success"`
}

// BatchEventResult defines model for BatchEventResult.
type BatchEventResult struct {
	// Error Error message if parsing this target failed
	Error   *string `json:"error,omitempty"`
	Event   *Event  `json:"event,omitempty"`
	Success bool    `json:"success"`

	// Target Requested target URL or ID
	Target string `json:"target"`
}

// BatchParseRequest defines model for BatchParseRequest.
type BatchParseRequest struct {
	// Refresh Bypass cache and force refresh
	Refresh *bool `json:"refresh,omitempty"`

	// Targets List of event URLs or IDs to parse
	Targets []string `json:"targets"`
}

// CustomizeQuestion defines model for CustomizeQuestion.
type CustomizeQuestion struct {
	Id       *string                 `json:"id,omitempty"`
	Label    *string                 `json:"label,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Options  *[]string               `json:"options,omitempty"`
	Required *bool                   `json:"required,omitempty"`
	Type     *string                 `json:"type,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ApiVersion string `json:"apiVersion"`

	// Code Machine-readable error classification code
	Code *string `json:"code,omitempty"`

	// Details Additional diagnostic information or validation errors
	Details *[]string `json:"details,omitempty"`

	// Error Human-readable error description
	Error   string `json:"error"`
	Success bool   `json:"success"`
}

// Event defines model for Event.
type Event struct {
	Artists *[]Artist `json:"artists,omitempty"`

	// Detail Event description and notes
	Detail *string `json:"detail,omitempty"`

	// Id Internal event ID (e.g. Firestore document ID)
	Id string `json:"id"`

	// Images Flyer and banner image URLs
	Images *[]string `json:"images,omitempty"`

	// Metadata Extensible dictionary for future or platform-specific attributes
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Name Event title
	Name string `json:"name"`

	// Release Information release date
	Release *string `json:"release,omitempty"`

	// ShortUrl Shortened event URL
	ShortUrl string `json:"shortUrl"`

	// Slug Event URL slug identifier
	Slug   string   `json:"slug"`
	Stages *[]Stage `json:"stages,omitempty"`

	// Stats Aggregated statistical indicators for the event
	Stats        *EventStats    `json:"stats,omitempty"`
	TicketGroups *[]TicketGroup `json:"ticketGroups,omitempty"`

	// Url Canonical event URL
	Url string `json:"url"`
}

// EventResponse defines model for EventResponse.
type EventResponse struct {
	ApiVersion string `json:"apiVersion"`
	Cached     bool   `json:"cached"`

	// CachedAt Timestamp when the cache entry was created
	CachedAt *time.Time `json:"cachedAt,omitempty"`
	Data     Event      `json:"data"`

	// Source Upstream source provenance and platform details
	Source  *SourceMetadata `json:"source,omitempty"`
	Success bool            `json:"success"`
}

// EventStats Aggregated statistical indicators for the event
type EventStats struct {
	// HasAvailableTickets Whether at least one ticket type remains available
	HasAvailableTickets *bool `json:"hasAvailableTickets,omitempty"`

	// MaxPrice Highest available ticket price
	MaxPrice *int `json:"maxPrice,omitempty"`

	// MinPrice Lowest available ticket price
	MinPrice *int `json:"minPrice,omitempty"`

	// SoldOutTicketTypes Number of sold out ticket types
	SoldOutTicketTypes *int `json:"soldOutTicketTypes,omitempty"`

	// TotalTicketTypes Total number of distinct ticket types
	TotalTicketTypes *int `json:"totalTicketTypes,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Service   string `json:"service"`
	Status    string `json:"status"`
	Timestamp int64  `json:"timestamp"`
	Version   string `json:"version"`
}

// ParseRequest defines model for ParseRequest.
type ParseRequest struct {
	// Id TicketDive event ID
	Id *string `json:"id,omitempty"`

	// Refresh Bypass cache and force refresh
	Refresh *bool `json:"refresh,omitempty"`

	// Url TicketDive event URL
	Url *string `json:"url,omitempty"`
}

// SourceMetadata Upstream source provenance and platform details
type SourceMetadata struct {
	// BuildId Next.js upstream build ID
	BuildId *string `json:"buildId,omitempty"`

	// FetchedAt Upstream fetch timestamp
	FetchedAt *time.Time `json:"fetchedAt,omitempty"`

	// Platform Source ticketing platform
	Platform *string `json:"platform,omitempty"`

	// ServerTime Server timestamp reported by upstream
	ServerTime *int64 `json:"serverTime,omitempty"`

	// Url Original source URL
	Url *string `json:"url,omitempty"`
}

// Stage defines model for Stage.
type Stage struct {
	Artists *[]Artist `json:"artists,omitempty"`

	// EndAt Estimated or scheduled finish time (ISO 8601)
	EndAt *string `json:"endAt,omitempty"`
	Id    string  `json:"id"`

	// Metadata Extensible stage metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// OpenAt Doors open time (ISO 8601)
	OpenAt    *string `json:"openAt,omitempty"`
	StageName string  `json:"stageName"`

	// StartAt Show start time (ISO 8601)
	StartAt *string `json:"startAt,omitempty"`

	// Timetable Optional slot-by-slot schedule if resolved
	Timetable *[]TimetableSlot `json:"timetable,omitempty"`
	Venue     *Venue           `json:"venue,omitempty"`
}

// TicketGroup defines model for TicketGroup.
type TicketGroup struct {
	Customize *[]CustomizeQuestion `json:"customize,omitempty"`

	// EndApply Application end timestamp (ISO 8601)
	EndApply *string                 `json:"endApply,omitempty"`
	Id       string                  `json:"id"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Name Group name (e.g. 一般販売, 最前OP 一般販売, FC先行販売)
	Name            string    `json:"name"`
	PaymentChannels *[]string `json:"paymentChannels,omitempty"`

	// ReceptionType Reception method (first=先着, lottery=抽選)
	ReceptionType string `json:"receptionType"`

	// Restrictions Rules such as untransferable, fcOnly, phoneNumberNeeded
	Restrictions *[]string `json:"restrictions,omitempty"`

	// StartApply Application start timestamp (ISO 8601)
	StartApply *string `json:"startApply,omitempty"`

	// Status Current reception status (e.g. applied, closed, upcoming)
	Status *string      `json:"status,omitempty"`
	Types  []TicketType `json:"types"`
}

// TicketType defines model for TicketType.
type TicketType struct {
	// Currency Three-letter ISO 4217 currency code
	Currency *string `json:"currency,omitempty"`
	Detail   *string `json:"detail,omitempty"`

	// Fee Handling fee
	Fee *int   `json:"fee,omitempty"`
	Id  string `json:"id"`

	// IsSoldOut Whether this ticket type is currently sold out
	IsSoldOut bool `json:"isSoldOut"`

	// MaxNumPerApply Maximum tickets allowed per application
	MaxNumPerApply *int `json:"maxNumPerApply,omitempty"`

	// Metadata Extensible vendor-specific ticket attributes
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     string                  `json:"name"`

	// Prefix Ticket reference number prefix (e.g. IA, IB, IHS)
	Prefix *string `json:"prefix,omitempty"`

	// Price Base ticket price
	Price int `json:"price"`

	// RemainingRate Stock ratio (1.0 = in stock, 0.0 = sold out)
	RemainingRate *float32 `json:"remainingRate,omitempty"`

	// Status Status string from upstream (applied, closed, etc.)
	Status *string `json:"status,omitempty"`

	// TotalPrice Combined price and fee
	TotalPrice *int `json:"totalPrice,omitempty"`
}

// TimetableSlot defines model for TimetableSlot.
type TimetableSlot struct {
	ArtistId   *string                 `json:"artistId,omitempty"`
	ArtistName string                  `json:"artistName"`
	EndAt      *time.Time              `json:"endAt,omitempty"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`

	// ParallelOrder Stage or parallel group index
	ParallelOrder *int       `json:"parallelOrder,omitempty"`
	StartAt       *time.Time `json:"startAt,omitempty"`
}

// Venue defines model for Venue.
type Venue struct {
	Address  *string                 `json:"address,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     *string                 `json:"name,omitempty"`

	// Url Venue official website or map URL
	Url *string `json:"url,omitempty"`
}

// GetEventByUrlParams defines parameters for GetEventByUrl.
type GetEventByUrlParams struct {
	// Url TicketDive URL (full or shortened, e.g. https://ticketdive.com/event/plkt1022 or https://t-dv.com/plkt1022)
	Url string `form:"url" json:"url"`

	// Refresh Bypass cache and force refresh from upstream
	Refresh *bool `form:"refresh,omitempty" json:"refresh,omitempty"`
}

// GetEventByIdParams defines parameters for GetEventById.
type GetEventByIdParams struct {
	// Refresh Bypass cache and force refresh from upstream
	Refresh *bool `form:"refresh,omitempty" json:"refresh,omitempty"`
}

// BatchParseEventsJSONRequestBody defines body for BatchParseEvents for application/json ContentType.
type BatchParseEventsJSONRequestBody = BatchParseRequest

// ParseEventJSONRequestBody defines body for ParseEvent for application/json ContentType.
type ParseEventJSONRequestBody = ParseRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetEventByUrl request
	GetEventByUrl(ctx context.Context, params *GetEventByUrlParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BatchParseEventsWithBody request with any body
	BatchParseEventsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BatchParseEvents(ctx context.Context, body BatchParseEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ParseEventWithBody request with any body
	ParseEventWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ParseEvent(ctx context.Context, body ParseEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEventById request
	GetEventById(ctx context.Context, eventId string, params *GetEventByIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEventIcal request
	GetEventIcal(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetEventByUrl(ctx context.Context, params *GetEventByUrlParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEventByUrlRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BatchParseEventsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBatchParseEventsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BatchParseEvents(ctx context.Context, body BatchParseEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBatchParseEventsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ParseEventWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParseEventRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ParseEvent(ctx context.Context, body ParseEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParseEventRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEventById(ctx context.Context, eventId string, params *GetEventByIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEventByIdRequest(c.Server, eventId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEventIcal(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEventIcalRequest(c.Server, eventId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetEventByUrlRequest generates requests for GetEventByUrl
func NewGetEventByUrlRequest(server string, params *GetEventByUrlParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "url", runtime.ParamLocationQuery, params.Url); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Refresh != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "refresh", runtime.ParamLocationQuery, *params.Refresh); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBatchParseEventsRequest calls the generic BatchParseEvents builder with application/json body
func NewBatchParseEventsRequest(server string, body BatchParseEventsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBatchParseEventsRequestWithBody(server, "application/json", bodyReader)
}

// NewBatchParseEventsRequestWithBody generates requests for BatchParseEvents with any type of body
func NewBatchParseEventsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events/batch")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewParseEventRequest calls the generic ParseEvent builder with application/json body
func NewParseEventRequest(server string, body ParseEventJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewParseEventRequestWithBody(server, "application/json", bodyReader)
}

// NewParseEventRequestWithBody generates requests for ParseEvent with any type of body
func NewParseEventRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events/parse")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetEventByIdRequest generates requests for GetEventById
func NewGetEventByIdRequest(server string, eventId string, params *GetEventByIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "eventId", runtime.ParamLocationPath, eventId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Refresh != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "refresh", runtime.ParamLocationQuery, *params.Refresh); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEventIcalRequest generates requests for GetEventIcal
func NewGetEventIcalRequest(server string, eventId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "eventId", runtime.ParamLocationPath, eventId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events/%s/ical", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetEventByUrlWithResponse request
	GetEventByUrlWithResponse(ctx context.Context, params *GetEventByUrlParams, reqEditors ...RequestEditorFn) (*GetEventByUrlResponse, error)

	// BatchParseEventsWithBodyWithResponse request with any body
	BatchParseEventsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BatchParseEventsResponse, error)

	BatchParseEventsWithResponse(ctx context.Context, body BatchParseEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*BatchParseEventsResponse, error)

	// ParseEventWithBodyWithResponse request with any body
	ParseEventWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ParseEventResponse, error)

	ParseEventWithResponse(ctx context.Context, body ParseEventJSONRequestBody, reqEditors ...RequestEditorFn) (*ParseEventResponse, error)

	// GetEventByIdWithResponse request
	GetEventByIdWithResponse(ctx context.Context, eventId string, params *GetEventByIdParams, reqEditors ...RequestEditorFn) (*GetEventByIdResponse, error)

	// GetEventIcalWithResponse request
	GetEventIcalWithResponse(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*GetEventIcalResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)
}

type GetEventByUrlResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetEventByUrlResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEventByUrlResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BatchParseEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BatchEventResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r BatchParseEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BatchParseEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ParseEventResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ParseEventResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ParseEventResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEventByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetEventByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEventByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEventIcalResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetEventIcalResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEventIcalResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetEventByUrlWithResponse request returning *GetEventByUrlResponse
func (c *ClientWithResponses) GetEventByUrlWithResponse(ctx context.Context, params *GetEventByUrlParams, reqEditors ...RequestEditorFn) (*GetEventByUrlResponse, error) {
	rsp, err := c.GetEventByUrl(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEventByUrlResponse(rsp)
}

// BatchParseEventsWithBodyWithResponse request with arbitrary body returning *BatchParseEventsResponse
func (c *ClientWithResponses) BatchParseEventsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BatchParseEventsResponse, error) {
	rsp, err := c.BatchParseEventsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBatchParseEventsResponse(rsp)
}

func (c *ClientWithResponses) BatchParseEventsWithResponse(ctx context.Context, body BatchParseEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*BatchParseEventsResponse, error) {
	rsp, err := c.BatchParseEvents(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBatchParseEventsResponse(rsp)
}

// ParseEventWithBodyWithResponse request with arbitrary body returning *ParseEventResponse
func (c *ClientWithResponses) ParseEventWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ParseEventResponse, error) {
	rsp, err := c.ParseEventWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParseEventResponse(rsp)
}

func (c *ClientWithResponses) ParseEventWithResponse(ctx context.Context, body ParseEventJSONRequestBody, reqEditors ...RequestEditorFn) (*ParseEventResponse, error) {
	rsp, err := c.ParseEvent(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParseEventResponse(rsp)
}

// GetEventByIdWithResponse request returning *GetEventByIdResponse
func (c *ClientWithResponses) GetEventByIdWithResponse(ctx context.Context, eventId string, params *GetEventByIdParams, reqEditors ...RequestEditorFn) (*GetEventByIdResponse, error) {
	rsp, err := c.GetEventById(ctx, eventId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEventByIdResponse(rsp)
}

// GetEventIcalWithResponse request returning *GetEventIcalResponse
func (c *ClientWithResponses) GetEventIcalWithResponse(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*GetEventIcalResponse, error) {
	rsp, err := c.GetEventIcal(ctx, eventId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEventIcalResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ParseGetEventByUrlResponse parses an HTTP response from a GetEventByUrlWithResponse call
func ParseGetEventByUrlResponse(rsp *http.Response) (*GetEventByUrlResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEventByUrlResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseBatchParseEventsResponse parses an HTTP response from a BatchParseEventsWithResponse call
func ParseBatchParseEventsResponse(rsp *http.Response) (*BatchParseEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BatchParseEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BatchEventResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseParseEventResponse parses an HTTP response from a ParseEventWithResponse call
func ParseParseEventResponse(rsp *http.Response) (*ParseEventResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ParseEventResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetEventByIdResponse parses an HTTP response from a GetEventByIdWithResponse call
func ParseGetEventByIdResponse(rsp *http.Response) (*GetEventByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEventByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetEventIcalResponse parses an HTTP response from a GetEventIcalWithResponse call
func ParseGetEventIcalResponse(rsp *http.Response) (*GetEventIcalResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEventIcalResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Event by URL Query
	// (GET /api/v1/events)
	GetEventByUrl(w http.ResponseWriter, r *http.Request, params GetEventByUrlParams)
	// Batch Parse Events
	// (POST /api/v1/events/batch)
	BatchParseEvents(w http.ResponseWriter, r *http.Request)
	// Parse Event
	// (POST /api/v1/events/parse)
	ParseEvent(w http.ResponseWriter, r *http.Request)
	// Get Event by ID
	// (GET /api/v1/events/{eventId})
	GetEventById(w http.ResponseWriter, r *http.Request, eventId string, params GetEventByIdParams)
	// Get Event iCalendar Feed
	// (GET /api/v1/events/{eventId}/ical)
	GetEventIcal(w http.ResponseWriter, r *http.Request, eventId string)
	// Health Check
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEventByUrl operation middleware
func (siw *ServerInterfaceWrapper) GetEventByUrl(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventByUrlParams

	// ------------- Required query parameter "url" -------------

	if paramValue := r.URL.Query().Get("url"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "url"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "url", r.URL.Query(), &params.Url)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "url", Err: err})
		return
	}

	// ------------- Optional query parameter "refresh" -------------

	err = runtime.BindQueryParameter("form", true, false, "refresh", r.URL.Query(), &params.Refresh)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refresh", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventByUrl(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BatchParseEvents operation middleware
func (siw *ServerInterfaceWrapper) BatchParseEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BatchParseEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ParseEvent operation middleware
func (siw *ServerInterfaceWrapper) ParseEvent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ParseEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventById operation middleware
func (siw *ServerInterfaceWrapper) GetEventById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId string

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventByIdParams

	// ------------- Optional query parameter "refresh" -------------

	err = runtime.BindQueryParameter("form", true, false, "refresh", r.URL.Query(), &params.Refresh)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refresh", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventById(w, r, eventId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventIcal operation middleware
func (siw *ServerInterfaceWrapper) GetEventIcal(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId string

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventIcal(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/events", wrapper.GetEventByUrl)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/events/batch", wrapper.BatchParseEvents)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/events/parse", wrapper.ParseEvent)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/events/{eventId}", wrapper.GetEventById)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/events/{eventId}/ical", wrapper.GetEventIcal)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa7W8cx3n/VybbfpCBI2/vRFIyAQPlq3WJRFIkRTc2DGNu97m7EWdnljOzFM8CAZ1Y",
	"qfQbgrRJiqIJmiJ10Bc3qZMPtR25/mNWpOVP+ReKmdm9272bI48R6baAv0i83WfneeZ5/T3PzEMv4FHM",
	"GTAlvfmHngw6EGHz54JQRCr9Vyx4DEIRMM9JqP8NQQaCxIpw5s1ntEjSpI24QI1lr+LBAY5iCt681+EM",
	"ujImAUwJ8Cqe6sb6sVSCsLZ3WPEiUDjECuuFcRgSvSqmGwW2SiTQ/5A370Og9IcMRzBWmpDImOIuMkRF",
	"edKjH6VHH6RHz9LHn6dHP04f/3P6+PNNmHaJlgg6ymBD8BahoLe6TYJdUMtkHxC2bO9t3i7vXqlYzler",
	"ylCGZB+mAx5VLXX1HN0cVjwBewkREHrzb2ndZ5t+26GNRayCzso+MLUJMuZMwqj1cEx2QEizj4cFKWvT",
	"vmv7AmRCrWsQBZH5488FtLx578+qA9epZn5TLYmQUCNWtigWAnf1b5kEAUhZ4l+yb5NzCpiN7L4g+2CV",
	"gYznqkTLM6IQEIKLUROv6McoAilxGxBpoRgLSVgbqQ6RSGHRBoVamFAIXXoDzfI8ZRm5hjQyrIKKZ3mN",
	"SrgJewlIBWEuzb3N2/3gO9uNsiUHjMeqbgMLCRmnUd0JaAmQHStbCxv9tjCVUBmSdbEbYylRgIMOIMxC",
	"1OIiAJR/Xxm7bTm679s6yHgLGRXrTUu7a4kUN1YqBftbXkx3Vc2v173KIBSnwn0ThKrdfqfm+3NaAX3/",
	"HjFm2YGdunSrcCmRikfkXbir9ZfFnCubjrCkuAm0HKFp7/2v/+E3J1/+bdr7ddr7zclff3H67CcvHj1J",
	"H//N6U//Pu0dm+c/Snu/THs/TXt/9cdnxydfPfnml8d/fPbepSZdbixRzgnn6KyosnOjPn9S3LwEqrm7",
	"HHtEPhO6l5YBAx46SswdHHQI0zkbh7hJAZk0ggKKpSQtEmBNh8y3xVqwsrOytv3O2vr2O6vr99aWXfxC",
	"UJhQh98v9G2EQoLbjEtFAkRYi4vIsuMC7WNKQvvLSKTz4+RGGpMLbyURZsNbLZKUtmjCknGFWjxhzuTo",
	"KgBZ2vjTKoCV2xWBK3keHvIBU3wnL2sZFnKozJrLUT+MGgrPTNpjXIF0qcQFqhpMgdDmtpmusYyuwXR7",
	"Gq0SAVJxASjkQRLZd6+UjBCKxsZdWr/+5k6Td2qLb9ztznWdbCPcBoevrdIuCCNxEzMGAhlCk2wv5FCT",
	"5pgh3R0oYJJoXwtJYL4RXV0yUCtRiTC4K6ZYac+fkjEEOuIQVkqQZlJS8HlI0VpJEUXLcVr363PVml+t",
	"16+d/vxfXkHpow+//uTHae/pNz97lPb+Pe39Nj36u/To39Kjj9PeR2nvH9PHH3zveyh99NFfvLF+Z/F2",
	"Y2fFjaYoYAkuUw+iOCNCIVajQk35r07Vb27Xrs/7/rzvT/u+/6YzxDpcqHsu7Lql3wCDcFBA3XA1r5GF",
	"+jnKhibtcVrVcMQ0BCQEpkiLgCgxOnNdlfvlROG5pcmdUFNhJSeCYVuGUi9hYPrrgifx5AJsDz5yieFs",
	"IpYw44wE/fiesG8wxGcYxdUxGDNlMWClKXjI2LR5eSVUw75wknSf0y448O42iUAqHMXoQQcYUh3I8CQw",
	"JbroAZYoEICVAeQ2nHQmxAqmFImcfWeemiYD6TwRAZzriobqTp73rqDdybSZST/Welu56w+hiHZbQFtr",
	"CengIBpEYIoICzVo4UKaPKuVa1uYypDpO1gu7GNCNRKwXu9g8kYHVEcXEIV0LlOIM0DWj5GWFgmIMGES",
	"4XypouePQ4URPtgQJHCkz1uk3QGpBsvlzGJDX1h7pu77/bUJU9AGYdYmbMzat/mDyZau+e6lJafheqKs",
	"sra7saveriVRE4TuajQ14okqqksW2cy6eCiuMD2Tw7amQKzPJ9SWZ8F4PjXHZlxo+xZgqjrjc4UEsZ8p",
	"dpAoaBIRndHG5H6VlMPF47suSpVnhBJx7cartes3btx81a/79UImIEzNzXgu7e2PyWWubDYUo5mwlf42",
	"B6sV5XNF6dmttQsQFmZNOSScuKJeZavuLG8jwl5efRtR5VDSHZHlXiyVABwhm8NRLPg+MMwCu8McS6K8",
	"9xpOes2E0LDhsMgaHKjp+xIlOQNDOWyX5R9s8O3mwcJeY0vCO/5fLq4kuz9wGakFalz162/B0KCBa01a",
	"6/JNOhChVYq1A2Htvj5KmxiYyRm0IPZB6BLtWN+8G4iMBMQag4ao2e1rzpsoUp2eti5Im+g+KbPuVTqa",
	"AZpX2E4Cc1p/RSoSmaLNBdKrhAmFELUII9I6A7rW2FpHN+f82iujTUPNn6rXt2v+OU0DKWM0b7N7e/bm",
	"3sFNfidaUO/iOFx584cvM0ka2+UZuI/6yzhnTsBcilnmGrLot5NqwZ+br82e2TppYdaydnGwxFl9nVRY",
	"KJd4Wx3+AJm3FxBv5kzx9DrKQKbRQIiz+ZCkXE01u1P6/767INJCAiSn+wY9TtjXZMy2KHf66z6w5FxM",
	"vGOI3J1JX9muEllsq0aCLsiHqxOH3eg4dkwExjHtOqBzHNN8sgcsLCS0SzDrcOyt3NqZu7kX72398O5i",
	"fS/8/usL98m3cHRmdG1OzLJh0/PPHr04/uTF7/715Fe/q6DTnz86ee+j9Y2hx6tLJ0+OX/zTh/Z3WQlF",
	"Smddwt0ImFrqYMaAlnHfW16AhXaTXc6ahJGLjOm1swVg9rWdjZOHz0+y1zrxdHiIrrWIkOq1kyfHX//i",
	"UQVRrhSI7mun73/5Te+z8qYM5ZjzMiXszMoBwjcTChLJJOggLFHClMBMtkDoCKugVrDOaLeC4g5nYDuC",
	"NYDQRGtBJeXPLqYSm6jOd+9ByprIwf36dq123kSqD+uHxiCJEBoe9q2FLGXmf1hLBWEFBZRL/X8SBzwi",
	"rF2WJCNzJsy8IbrAJMd4zHknP4PD2GFfy5mOz2m5Sw6nNK2LoFtC6d73N3TVHULXHQEwRUG7KNLGmanX",
	"bqD8+9GDB7vGmMOGoXOmo/fMZPP36ePfPv/Dr06OP77h+ydPn77472dp76vq3Ol//P75Hz5+/tn76VEv",
	"ffxpenSUHh2ffPXkxa97bkzratgxC6mGmvptQc7rM84Wejg5zsLunebyRm2nE9T22g01B+q+M6nKLdt8",
	"jx9R2OPcwmiCyEyNinb73XhRxrGjqwgfrCXRBogxAXYHH5AoiTJuEmFK+QMIUQzCurkNvtK4wjmreFm4",
	"tQ8s5GIwOc+2P9kAfTizn7z30enPPi/6gjPLC2iRg3Fdou4uQXsu5BMKS5/lgMZCBTUWK6hxa6sc9Y0F",
	"Ny/nIGcRy4vPheygirD2Jlau1kbxYBcJbTd0rTbto9cQ0QmMB7sV5JvfuQuVJK/1edn9npUgt2w6tPtD",
	"LcGjQbt5bSQ9ggqmJ0+NXGnHcapriUdNwrR76vd2ElAO1pnZGfeMaFySzLU+CEt3gixizjG9VsN9bG5f",
	"5uB99FZG3l1N1jL/ydgqxgJTCnRdhCCcFm3bQ6yMDrUN7CIshANn31toMCYRfXiQPNCKS+E7OYYfUnQY",
	"iuG5tXf6i0+ff/HJN0dfnn72wYv//K+TD784efr05NNPv/7JF/Wp2tyVINTJejDnaMBsDfFWiwQEU/QA",
	"mpIoo/oIx9mg4Ny2Xz8irMUnmHHhEMcKRKXfy6JY8INuBTWxCjq2/Ur0xxUTUGQJU2AhFjq0QtQGBgIr",
	"Lqa9ikdJANlA1SrCu9PYzk5vBjMN3fnascc0F+1q9pGsalrTLKrSvBUtbDQKI8p8ypk12Dgm3rx3fdqf",
	"vq6jFauOsX4Vx6S6X7MDE/PEeR9p1QyvTKJKApWI/gljXxfNLrI1p2svUhUmgxoPY7SXgOiaqIhAgVGD",
	"9hJTFnXEe6+DMocbi9175hCrTyq9+bfOsI7mcK2VUGrmJ/kJaAWZ8jLRfEh/OPZoVCdcolmaDeQJbz47",
	"aRuEonV0CzUdCeqw8vBCw9hyMRgjw2BwO+A7PAEeOYh623QyZqJvDF73fYNPOVPZfYoCYKnel3Z4PmBw",
	"7oFa/7zARJf76oSdxR5WvJnL5F66HOTg3mDmDg3KJ/OHFW/22+Wf3frIxqbmA5OWZBJFWHRtGCCrpWbX",
	"+PZdY3NNVA7Wqsk7Jrdz6bxDaOZB0o7BsZAgUZRQRWIKaDi7SY1tMJKEtSmgAFM6GqCDS4MrNltY9wep",
	"FnnYvTQtjt5NPCwXPR1ph1foxI6rtg5bGiqrV5TfUv3On0f92erJ2BNlfuPwZXu3c6wvLwS6BddlZCjx",
	"m9uh2nd1xcm8ETV52DVeL0AlgpXKVl6wRt174NlX5Nj/mz79XWJ+aUcuuLDLgx+a/xvh4UuAKFPzCx7e",
	"7A7uB2pwQ5P2WbipEV4ANhUX7l/nsj35CPTRcHGAOrKNfod+/v8H2Yw/8+3xt7tf4wqtmtvD/+fRV2P5",
	"zECvkgDTsdH+um34DP4qNIPXpkkgX0Gbq0todnZmVkOtQpeY38/Kxnd5hhgf9A0twssF/eUF+fmxpeBA",
	"VfMtl007vNiI+coN9Xfee6b3DpS1apSl3bhjbnO9O9ZjNzO0ZOnyoxqdm7OZAuIt1J82ZJeinK5p7415",
	"V5hqh26mOfRlKbpDGrJP0VIHgl37lb3d4oqb2zzAFIWwD5TH5iq+pS0NauarVarpOlyq+Zv+Td87fPvw",
	"fwIAAP//eUl5Uno5AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
