//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Artist defines model for Artist.
type Artist struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// CustomizeQuestion defines model for CustomizeQuestion.
type CustomizeQuestion struct {
	Label    *string   `json:"label,omitempty"`
	Options  *[]string `json:"options,omitempty"`
	Required *bool     `json:"required,omitempty"`
	Type     *string   `json:"type,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   string `json:"error"`
	Success bool   `json:"success"`
}

// Event defines model for Event.
type Event struct {
	Artists *[]Artist `json:"artists,omitempty"`

	// Detail Event description and notes
	Detail *string `json:"detail,omitempty"`

	// Id Internal event ID
	Id string `json:"id"`

	// Images Flyer image URLs
	Images *[]string `json:"images,omitempty"`

	// Name Event title
	Name string `json:"name"`

	// Release Information release date
	Release *string `json:"release,omitempty"`

	// ShortUrl Shortened event URL
	ShortUrl string `json:"shortUrl"`

	// Slug Event URL slug
	Slug         string         `json:"slug"`
	Stages       *[]Stage       `json:"stages,omitempty"`
	TicketGroups *[]TicketGroup `json:"ticketGroups,omitempty"`

	// Url Canonical event URL
	Url string `json:"url"`
}

// EventResponse defines model for EventResponse.
type EventResponse struct {
	Cached  bool  `json:"cached"`
	Data    Event `json:"data"`
	Success bool  `json:"success"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Service   string `json:"service"`
	Status    string `json:"status"`
	Timestamp int64  `json:"timestamp"`
}

// ParseRequest defines model for ParseRequest.
type ParseRequest struct {
	// Id TicketDive event ID
	Id *string `json:"id,omitempty"`

	// Url TicketDive event URL
	Url *string `json:"url,omitempty"`
}

// Stage defines model for Stage.
type Stage struct {
	Artists *[]Artist `json:"artists,omitempty"`
	Id      string    `json:"id"`

	// OpenAt Doors open time
	OpenAt    *string `json:"openAt,omitempty"`
	StageName string  `json:"stageName"`

	// StartAt Show start time
	StartAt *string `json:"startAt,omitempty"`
	Venue   *Venue  `json:"venue,omitempty"`
}

// TicketGroup defines model for TicketGroup.
type TicketGroup struct {
	Customize *[]CustomizeQuestion `json:"customize,omitempty"`

	// EndApply Application end timestamp
	EndApply *string `json:"endApply,omitempty"`
	Id       string  `json:"id"`

	// Name Group name (e.g. 一般販売, 最前OP 一般販売)
	Name            string    `json:"name"`
	PaymentChannels *[]string `json:"paymentChannels,omitempty"`

	// ReceptionType Reception type (first=先着, lottery=抽選)
	ReceptionType string `json:"receptionType"`

	// StartApply Application start timestamp
	StartApply *string      `json:"startApply,omitempty"`
	Status     *string      `json:"status,omitempty"`
	Types      []TicketType `json:"types"`
}

// TicketType defines model for TicketType.
type TicketType struct {
	Detail *string `json:"detail,omitempty"`
	Fee    *int    `json:"fee,omitempty"`
	Id     string  `json:"id"`

	// IsSoldOut Whether this ticket type is sold out
	IsSoldOut bool `json:"isSoldOut"`

	// MaxNumPerApply Maximum tickets per application
	MaxNumPerApply *int   `json:"maxNumPerApply,omitempty"`
	Name           string `json:"name"`

	// Prefix Ticket number prefix
	Prefix *string `json:"prefix,omitempty"`
	Price  int     `json:"price"`

	// RemainingRate Stock ratio (1 = remaining, 0 = sold out)
	RemainingRate *float32 `json:"remainingRate,omitempty"`

	// Status Status string (applied, closed)
	Status *string `json:"status,omitempty"`
}

// Venue defines model for Venue.
type Venue struct {
	Address *string `json:"address,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// GetEventByUrlParams defines parameters for GetEventByUrl.
type GetEventByUrlParams struct {
	// Url TicketDive URL (full or shortened, e.g. https://ticketdive.com/event/plkt1022 or https://t-dv.com/plkt1022)
	Url string `form:"url" json:"url"`
}

// ParseEventJSONRequestBody defines body for ParseEvent for application/json ContentType.
type ParseEventJSONRequestBody = ParseRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetEventByUrl request
	GetEventByUrl(ctx context.Context, params *GetEventByUrlParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ParseEventWithBody request with any body
	ParseEventWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ParseEvent(ctx context.Context, body ParseEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEventById request
	GetEventById(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEventIcal request
	GetEventIcal(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetEventByUrl(ctx context.Context, params *GetEventByUrlParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEventByUrlRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ParseEventWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParseEventRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ParseEvent(ctx context.Context, body ParseEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParseEventRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEventById(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEventByIdRequest(c.Server, eventId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEventIcal(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEventIcalRequest(c.Server, eventId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetEventByUrlRequest generates requests for GetEventByUrl
func NewGetEventByUrlRequest(server string, params *GetEventByUrlParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "url", runtime.ParamLocationQuery, params.Url); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewParseEventRequest calls the generic ParseEvent builder with application/json body
func NewParseEventRequest(server string, body ParseEventJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewParseEventRequestWithBody(server, "application/json", bodyReader)
}

// NewParseEventRequestWithBody generates requests for ParseEvent with any type of body
func NewParseEventRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events/parse")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetEventByIdRequest generates requests for GetEventById
func NewGetEventByIdRequest(server string, eventId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "eventId", runtime.ParamLocationPath, eventId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEventIcalRequest generates requests for GetEventIcal
func NewGetEventIcalRequest(server string, eventId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "eventId", runtime.ParamLocationPath, eventId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events/%s/ical", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetEventByUrlWithResponse request
	GetEventByUrlWithResponse(ctx context.Context, params *GetEventByUrlParams, reqEditors ...RequestEditorFn) (*GetEventByUrlResponse, error)

	// ParseEventWithBodyWithResponse request with any body
	ParseEventWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ParseEventResponse, error)

	ParseEventWithResponse(ctx context.Context, body ParseEventJSONRequestBody, reqEditors ...RequestEditorFn) (*ParseEventResponse, error)

	// GetEventByIdWithResponse request
	GetEventByIdWithResponse(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*GetEventByIdResponse, error)

	// GetEventIcalWithResponse request
	GetEventIcalWithResponse(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*GetEventIcalResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)
}

type GetEventByUrlResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetEventByUrlResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEventByUrlResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ParseEventResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ParseEventResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ParseEventResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEventByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetEventByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEventByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEventIcalResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetEventIcalResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEventIcalResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetEventByUrlWithResponse request returning *GetEventByUrlResponse
func (c *ClientWithResponses) GetEventByUrlWithResponse(ctx context.Context, params *GetEventByUrlParams, reqEditors ...RequestEditorFn) (*GetEventByUrlResponse, error) {
	rsp, err := c.GetEventByUrl(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEventByUrlResponse(rsp)
}

// ParseEventWithBodyWithResponse request with arbitrary body returning *ParseEventResponse
func (c *ClientWithResponses) ParseEventWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ParseEventResponse, error) {
	rsp, err := c.ParseEventWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParseEventResponse(rsp)
}

func (c *ClientWithResponses) ParseEventWithResponse(ctx context.Context, body ParseEventJSONRequestBody, reqEditors ...RequestEditorFn) (*ParseEventResponse, error) {
	rsp, err := c.ParseEvent(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParseEventResponse(rsp)
}

// GetEventByIdWithResponse request returning *GetEventByIdResponse
func (c *ClientWithResponses) GetEventByIdWithResponse(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*GetEventByIdResponse, error) {
	rsp, err := c.GetEventById(ctx, eventId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEventByIdResponse(rsp)
}

// GetEventIcalWithResponse request returning *GetEventIcalResponse
func (c *ClientWithResponses) GetEventIcalWithResponse(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*GetEventIcalResponse, error) {
	rsp, err := c.GetEventIcal(ctx, eventId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEventIcalResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ParseGetEventByUrlResponse parses an HTTP response from a GetEventByUrlWithResponse call
func ParseGetEventByUrlResponse(rsp *http.Response) (*GetEventByUrlResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEventByUrlResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseParseEventResponse parses an HTTP response from a ParseEventWithResponse call
func ParseParseEventResponse(rsp *http.Response) (*ParseEventResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ParseEventResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetEventByIdResponse parses an HTTP response from a GetEventByIdWithResponse call
func ParseGetEventByIdResponse(rsp *http.Response) (*GetEventByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEventByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetEventIcalResponse parses an HTTP response from a GetEventIcalWithResponse call
func ParseGetEventIcalResponse(rsp *http.Response) (*GetEventIcalResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEventIcalResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Event by URL Query
	// (GET /api/v1/events)
	GetEventByUrl(w http.ResponseWriter, r *http.Request, params GetEventByUrlParams)
	// Parse Event
	// (POST /api/v1/events/parse)
	ParseEvent(w http.ResponseWriter, r *http.Request)
	// Get Event by ID
	// (GET /api/v1/events/{eventId})
	GetEventById(w http.ResponseWriter, r *http.Request, eventId string)
	// Get Event iCalendar Feed
	// (GET /api/v1/events/{eventId}/ical)
	GetEventIcal(w http.ResponseWriter, r *http.Request, eventId string)
	// Health Check
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEventByUrl operation middleware
func (siw *ServerInterfaceWrapper) GetEventByUrl(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventByUrlParams

	// ------------- Required query parameter "url" -------------

	if paramValue := r.URL.Query().Get("url"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "url"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "url", r.URL.Query(), &params.Url)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "url", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventByUrl(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ParseEvent operation middleware
func (siw *ServerInterfaceWrapper) ParseEvent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ParseEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventById operation middleware
func (siw *ServerInterfaceWrapper) GetEventById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId string

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventById(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventIcal operation middleware
func (siw *ServerInterfaceWrapper) GetEventIcal(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId string

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventIcal(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/events", wrapper.GetEventByUrl)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/events/parse", wrapper.ParseEvent)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/events/{eventId}", wrapper.GetEventById)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/events/{eventId}/ical", wrapper.GetEventIcal)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZW28bxxX+K5NtH2SAJpeULMsEDFS2bIeFbMvUxYgNPwx3D8mxdndWM7Os1oYAUaxd",
	"2akRpG1SFE3RAKmDXtIETV7sRml+zFqy/JS/UMzs8rLcWUpOHCMPfrGF2Zk553znO7fhXcOirk898AQ3",
	"qncNbrXBxerPeSYIF/Ivn1EfmCCg1okt/4VN7PoOGFWjTT0IuU8sOMnAKBgi9OUyF4x4LWOrYHjYhfSR",
	"qPde1Hs36u1FO0+j3vvRzt+inad1KGZPbxUMBhsBYWAb1ZtSdnLfrcFW2rgNlpCCzgdcUJfcgWsBcEGo",
	"l1XewQ1wxpTpPnz+58/3v/l91P006n6+/5v/Huz94XD7XrTzu4MP/hR1d9X6e1H346j7QdT99Xd7u/vf",
	"3nvx8e53ew905lJfio6hEuCqPzKbkgXMGA6NlJEjqgkWwGBrg1IHsDc8PGoDB0dioIMvg9IFxiirA/ep",
	"xyGLEMjP6dsvdMATyKMCNWng2TqjeWBZwHnqXBM7XKP/mEv7JwuJZJ1jlQJZVbFiaBrpnzNoGlXjZ6Uh",
	"r0sJqUsJozXw2yAwUbywgVuM+DF7EstH1hD2bIkEcB0KcWikr6h5ApiHHQTqrtqCtHQArc1qS9ecyvSN",
	"tQZtl89dvxbOhtqbXdyKjU7fftEJgSH1Fa3WF6VWxyddPzB1NgsiHEipWjErs6WyWapUpg4++vsJFG3/",
	"9vln70fd+y8+3I66/4q6X0S9P0a9f0a9x1H3UdT9a7Tz7ltvoWj70S+uX718brG2dkFnGQMHMAcdcE3K",
	"XKxQTzYhG4usUifNMycrcyvl6appVk2zaJrmDS1H25SJVaZx87L8Ah7YiZNW64spKW0hfF4tlcRJu1O0",
	"qFvynXVRNisVrRgnaOWhulpfROr76O0TLxN9vx+L4ctyu87VgljrIC4xGvjHv21leEh3Z6CD8jz2qEes",
	"Ad9zoVR326QDClC1eQKsujqQAKlYHGsz4uPcNJKf+SxstccycE4KKxg2Fvgo+OKslZMc9bk9NzcmuiWC",
	"dca9DdgR7XzrOLAOscbqhhO4RPogh3oiSCtt0HXdTkFc4AK7fmpz+fSZ8vTp03NnzIpZKRhxMBtVg3hi",
	"dmZ4DfEEtIBlbY/FFwaKj8rRAbCEGYc6bMjan9e1pLka83uBdECfnCcFppb8mQtfHfsz5sah/iPWxPE+",
	"rx4unprb2Jyjl915cQf79oUb7+j7H/DmRRacBUoZR/Irko7MpvGyebJSWTFnq+VTE9O4NPxKpqecVGO4",
	"wEzodFpu018h9fUonWYm6tQBL4CjoF5Tm/SpbGCTjtmjeTibtfpN77Fdnm2TNd4Hz573fSfMYiaXiRXX",
	"ZfBsNIzK74veONMuvL02O7fhbyy/c+1cZcP+5aX522TSYJHWT+GE5Dc0BcVWET17sn24+9nhl//Y/+TL",
	"Ajr4aHv/waOrS6nlEyndR7/o5Po4dMET59vY88BJp8ibhoWZdOk69RrEI9KhLzMGWKDsWEla/LRp9f5n",
	"JA+iqSZhXJzdv7f7/C/bBeRQIYCFZw8efvOi+yRtktqZHxpHe3oYJPm+Nisr5fJRTZimqmApB7RzhVx4",
	"2YZFYZcBN3eSHEe9LzQ/EvvOSQficIYYHXQfqI74q2jni2dff7K/+/i0ae7fv3/4v72o+21p9uDfXz37",
	"+vGzJw+jXjfa+U/U60U9OV0eftrVodGEdNKbnjGzdTQbT6dg/XJjYam81rbKG62amAVxWxuHfJk69tVA",
	"kyivt0G0gSHRJhzF1SvmIOGIU8dGNBCjnMhtnFy8eSVwl4DlcO4y3iRu4CYyOPKBITzk4aiMGZ3t2ceG",
	"OJr3Hzw6+PDpKMzayGbQJJt5hR15gdsAhpJdoyFQm9dfN95xzVRMrcsYuJh4xGvV5YSTrVOCWuuISQjQ",
	"VBmdRYP9BWSiswMXpIK+PBAU650Ov3EBch3FqqOpJCILyHIoBzudS3LDdUKIxUiMUkwXXmv9MjrW09g2",
	"G++fjeO9NOV3BdmeSi4Rr0mP0ddhG/sCWAG5ILBsyZHP6GZYUM8D5Dx2wLMxQ00AG7XAA4YFZUWjYDjE",
	"gqQ9j5U1LtdWkull2B7KJonTgFlQpKxVSg7xktyr+m2R6t7R/FLNkE0I47G+5aJZNPu9GPaJUTWmi2Zx",
	"WjoCi7ZCsoR9UuqU495TrbRAE/gXQVhtUMwILBGwwYw8sLwRIu6DRZqhpI5oj/S+CHOE0UYALEQ+ZtgF",
	"AQoG6V0VzzVbVmwQalY6F66qIW6wlRvVmxN8ISVMNQPHQZQh3p/hC0hV/WO12vJg7nAvWU+kSGVAn8vV",
	"ZNIcMj0e5eIapKnyW7fk5ngsUzhXTFM1btQTybPWSIIr3ebxu+XwviNnzMHQpyisf8GStYlLSsy8Sump",
	"p0SN9JrXwQ6xUX8s2yoYp16v/OTxbRlYBxhSB1Ts88B1MQtj9qEYpUaoKHVNuVtuSsdIyZcTpkpPlGtC",
	"Zd6SbYRk/BhHKUO1BUQ8FRwshgI1qB2qdMFABMxLRVg/trKhoobc+GEhpiBwcY7a4SuDNDVFb6VTuiT6",
	"1hsy/5TJrNyHkpenLIPvqv9r9tYPyPdNRt1RhjfCweuJysNO0JqU4mv2S2T40Yv7b6fJVJfJ0rKyDZN0",
	"YuibRP29uT1jzrw++bH1V6hAF9VPTD/5QlFbmBhfJWJhJzfILsUtIXCEvZF2capILH4CNYkDqEmZKhdx",
	"a0X6YZgfWTUp8IdF1uuMJAGbomQllqcdOX5ZxlnpBvsNVydydQjWRQWWJG1b/VZwJ5ef9aQlifeheGhE",
	"tIkGE0fyKK+lY/xLhPEjJtOx3zo0GMU7wjFU4lV0vg3WenyKKwh1sbJILewgGzrgUN+VSMZ7U8NatVRy",
	"5L425aI6Z86Zxtatrf8HAAD///DukjlUIQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
