//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Artist defines model for Artist.
type Artist struct {
	// Id Artist slug or ID
	Id       string                  `json:"id"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Name Artist display name
	Name string `json:"name"`

	// Url Profile or TicketDive artist URL
	Url *string `json:"url,omitempty"`
}

// ArtistDetail defines model for ArtistDetail.
type ArtistDetail struct {
	Events *[]ArtistEvent `json:"events,omitempty"`

	// Id Artist slug or ID
	Id       string                  `json:"id"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Name Artist display name
	Name string `json:"name"`

	// ProfileImage Artist profile avatar image URL
	ProfileImage *string `json:"profileImage,omitempty"`

	// TwitterAccount Official Twitter / X account handle
	TwitterAccount *string `json:"twitterAccount,omitempty"`

	// Url Official TicketDive artist page URL
	Url *string `json:"url,omitempty"`
}

// ArtistDetailResponse defines model for ArtistDetailResponse.
type ArtistDetailResponse struct {
	ApiVersion string       `json:"apiVersion"`
	Cached     bool         `json:"cached"`
	CachedAt   *time.Time   `json:"cachedAt,omitempty"`
	Data       ArtistDetail `json:"data"`

	// Source Upstream source provenance and platform details
	Source  *SourceMetadata `json:"source,omitempty"`
	Success bool            `json:"success"`
}

// ArtistEvent defines model for ArtistEvent.
type ArtistEvent struct {
	// EndAt Event end date if specified
	EndAt *string `json:"endAt,omitempty"`

	// Id Event ID
	Id string `json:"id"`

	// ImageSource Event flyer/banner thumbnail URL
	ImageSource *string `json:"imageSource,omitempty"`

	// SalesStatus Current sales status (applied, closed, etc.)
	SalesStatus *string `json:"salesStatus,omitempty"`

	// Slug Event slug URL identifier
	Slug *string `json:"slug,omitempty"`

	// StartAt Event start or stage date (ISO 8601)
	StartAt *string `json:"startAt,omitempty"`

	// Title Event title
	Title string `json:"title"`

	// Url Event URL on TicketDive
	Url *string `json:"url,omitempty"`

	// VenueName Venue name
	VenueName *string `json:"venueName,omitempty"`
}

// BatchEventResponse defines model for BatchEventResponse.
type BatchEventResponse struct {
	ApiVersion string             `json:"apiVersion"`
	Results    []BatchEventResult `json:"results"`
	Success    bool               `json:"success"`
}

// BatchEventResult defines model for BatchEventResult.
type BatchEventResult struct {
	// Error Error message if parsing this target failed
	Error   *string `json:"error,omitempty"`
	Event   *Event  `json:"event,omitempty"`
	Success bool    `json:"success"`

	// Target Requested target URL or ID
	Target string `json:"target"`
}

// BatchParseRequest defines model for BatchParseRequest.
type BatchParseRequest struct {
	// Refresh Bypass cache and force refresh
	Refresh *bool `json:"refresh,omitempty"`

	// Targets List of event URLs or IDs to parse
	Targets []string `json:"targets"`
}

// CustomizeQuestion defines model for CustomizeQuestion.
type CustomizeQuestion struct {
	Id       *string                 `json:"id,omitempty"`
	Label    *string                 `json:"label,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Options  *[]string               `json:"options,omitempty"`
	Required *bool                   `json:"required,omitempty"`
	Type     *string                 `json:"type,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ApiVersion string `json:"apiVersion"`

	// Code Machine-readable error classification code
	Code *string `json:"code,omitempty"`

	// Details Additional diagnostic information or validation errors
	Details *[]string `json:"details,omitempty"`

	// Error Human-readable error description
	Error   string `json:"error"`
	Success bool   `json:"success"`
}

// Event defines model for Event.
type Event struct {
	Artists *[]Artist `json:"artists,omitempty"`

	// Detail Event description and notes
	Detail *string `json:"detail,omitempty"`

	// Id Internal event ID (e.g. Firestore document ID)
	Id string `json:"id"`

	// Images Flyer and banner image URLs
	Images *[]string `json:"images,omitempty"`

	// Metadata Extensible dictionary for future or platform-specific attributes
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Name Event title
	Name string `json:"name"`

	// Release Information release date
	Release *string `json:"release,omitempty"`

	// ShortUrl Shortened event URL
	ShortUrl string `json:"shortUrl"`

	// Slug Event URL slug identifier
	Slug   string   `json:"slug"`
	Stages *[]Stage `json:"stages,omitempty"`

	// Stats Aggregated statistical indicators for the event
	Stats        *EventStats    `json:"stats,omitempty"`
	TicketGroups *[]TicketGroup `json:"ticketGroups,omitempty"`

	// Url Canonical event URL
	Url string `json:"url"`
}

// EventResponse defines model for EventResponse.
type EventResponse struct {
	ApiVersion string `json:"apiVersion"`
	Cached     bool   `json:"cached"`

	// CachedAt Timestamp when the cache entry was created
	CachedAt *time.Time `json:"cachedAt,omitempty"`
	Data     Event      `json:"data"`

	// Source Upstream source provenance and platform details
	Source  *SourceMetadata `json:"source,omitempty"`
	Success bool            `json:"success"`
}

// EventStats Aggregated statistical indicators for the event
type EventStats struct {
	// HasAvailableTickets Whether at least one ticket type remains available
	HasAvailableTickets *bool `json:"hasAvailableTickets,omitempty"`

	// MaxPrice Highest available ticket price
	MaxPrice *int `json:"maxPrice,omitempty"`

	// MinPrice Lowest available ticket price
	MinPrice *int `json:"minPrice,omitempty"`

	// SoldOutTicketTypes Number of sold out ticket types
	SoldOutTicketTypes *int `json:"soldOutTicketTypes,omitempty"`

	// TotalTicketTypes Total number of distinct ticket types
	TotalTicketTypes *int `json:"totalTicketTypes,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Service   string `json:"service"`
	Status    string `json:"status"`
	Timestamp int64  `json:"timestamp"`
	Version   string `json:"version"`
}

// ParseRequest defines model for ParseRequest.
type ParseRequest struct {
	// Id TicketDive event ID
	Id *string `json:"id,omitempty"`

	// Refresh Bypass cache and force refresh
	Refresh *bool `json:"refresh,omitempty"`

	// Url TicketDive event URL
	Url *string `json:"url,omitempty"`
}

// SourceMetadata Upstream source provenance and platform details
type SourceMetadata struct {
	// BuildId Next.js upstream build ID
	BuildId *string `json:"buildId,omitempty"`

	// FetchedAt Upstream fetch timestamp
	FetchedAt *time.Time `json:"fetchedAt,omitempty"`

	// Platform Source ticketing platform
	Platform *string `json:"platform,omitempty"`

	// ServerTime Server timestamp reported by upstream
	ServerTime *int64 `json:"serverTime,omitempty"`

	// Url Original source URL
	Url *string `json:"url,omitempty"`
}

// Stage defines model for Stage.
type Stage struct {
	Artists *[]Artist `json:"artists,omitempty"`

	// EndAt Estimated or scheduled finish time (ISO 8601)
	EndAt *string `json:"endAt,omitempty"`
	Id    string  `json:"id"`

	// Metadata Extensible stage metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// OpenAt Doors open time (ISO 8601)
	OpenAt    *string `json:"openAt,omitempty"`
	StageName string  `json:"stageName"`

	// StartAt Show start time (ISO 8601)
	StartAt *string `json:"startAt,omitempty"`

	// Timetable Optional slot-by-slot schedule if resolved
	Timetable *[]TimetableSlot `json:"timetable,omitempty"`
	Venue     *Venue           `json:"venue,omitempty"`
}

// TicketGroup defines model for TicketGroup.
type TicketGroup struct {
	Customize *[]CustomizeQuestion `json:"customize,omitempty"`

	// EndApply Application end timestamp (ISO 8601)
	EndApply *string                 `json:"endApply,omitempty"`
	Id       string                  `json:"id"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Name Group name (e.g. 一般販売, 最前OP 一般販売, FC先行販売)
	Name            string    `json:"name"`
	PaymentChannels *[]string `json:"paymentChannels,omitempty"`

	// ReceptionType Reception method (first=先着, lottery=抽選)
	ReceptionType string `json:"receptionType"`

	// Restrictions Rules such as untransferable, fcOnly, phoneNumberNeeded
	Restrictions *[]string `json:"restrictions,omitempty"`

	// StartApply Application start timestamp (ISO 8601)
	StartApply *string `json:"startApply,omitempty"`

	// Status Current reception status (e.g. applied, closed, upcoming)
	Status *string      `json:"status,omitempty"`
	Types  []TicketType `json:"types"`
}

// TicketType defines model for TicketType.
type TicketType struct {
	// Currency Three-letter ISO 4217 currency code
	Currency *string `json:"currency,omitempty"`
	Detail   *string `json:"detail,omitempty"`

	// Fee Handling fee
	Fee *int   `json:"fee,omitempty"`
	Id  string `json:"id"`

	// IsSoldOut Whether this ticket type is currently sold out
	IsSoldOut bool `json:"isSoldOut"`

	// MaxNumPerApply Maximum tickets allowed per application
	MaxNumPerApply *int `json:"maxNumPerApply,omitempty"`

	// Metadata Extensible vendor-specific ticket attributes
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     string                  `json:"name"`

	// Prefix Ticket reference number prefix (e.g. IA, IB, IHS)
	Prefix *string `json:"prefix,omitempty"`

	// Price Base ticket price
	Price int `json:"price"`

	// RemainingRate Stock ratio (1.0 = in stock, 0.0 = sold out)
	RemainingRate *float32 `json:"remainingRate,omitempty"`

	// Status Status string from upstream (applied, closed, etc.)
	Status *string `json:"status,omitempty"`

	// TotalPrice Combined price and fee
	TotalPrice *int `json:"totalPrice,omitempty"`
}

// TimetableSlot defines model for TimetableSlot.
type TimetableSlot struct {
	ArtistId   *string                 `json:"artistId,omitempty"`
	ArtistName string                  `json:"artistName"`
	EndAt      *time.Time              `json:"endAt,omitempty"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`

	// ParallelOrder Stage or parallel group index
	ParallelOrder *int       `json:"parallelOrder,omitempty"`
	StartAt       *time.Time `json:"startAt,omitempty"`
}

// Venue defines model for Venue.
type Venue struct {
	Address  *string                 `json:"address,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Name     *string                 `json:"name,omitempty"`

	// Url Venue official website or map URL
	Url *string `json:"url,omitempty"`
}

// GetArtistByIdParams defines parameters for GetArtistById.
type GetArtistByIdParams struct {
	// Refresh Bypass cache and force refresh from upstream
	Refresh *bool `form:"refresh,omitempty" json:"refresh,omitempty"`
}

// GetEventByUrlParams defines parameters for GetEventByUrl.
type GetEventByUrlParams struct {
	// Url TicketDive URL (full or shortened, e.g. https://ticketdive.com/event/plkt1022 or https://t-dv.com/plkt1022)
	Url string `form:"url" json:"url"`

	// Refresh Bypass cache and force refresh from upstream
	Refresh *bool `form:"refresh,omitempty" json:"refresh,omitempty"`
}

// GetEventByIdParams defines parameters for GetEventById.
type GetEventByIdParams struct {
	// Refresh Bypass cache and force refresh from upstream
	Refresh *bool `form:"refresh,omitempty" json:"refresh,omitempty"`
}

// BatchParseEventsJSONRequestBody defines body for BatchParseEvents for application/json ContentType.
type BatchParseEventsJSONRequestBody = BatchParseRequest

// ParseEventJSONRequestBody defines body for ParseEvent for application/json ContentType.
type ParseEventJSONRequestBody = ParseRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetArtistById request
	GetArtistById(ctx context.Context, artistId string, params *GetArtistByIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetArtistIcal request
	GetArtistIcal(ctx context.Context, artistId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEventByUrl request
	GetEventByUrl(ctx context.Context, params *GetEventByUrlParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BatchParseEventsWithBody request with any body
	BatchParseEventsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BatchParseEvents(ctx context.Context, body BatchParseEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ParseEventWithBody request with any body
	ParseEventWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ParseEvent(ctx context.Context, body ParseEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEventById request
	GetEventById(ctx context.Context, eventId string, params *GetEventByIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEventIcal request
	GetEventIcal(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetArtistById(ctx context.Context, artistId string, params *GetArtistByIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetArtistByIdRequest(c.Server, artistId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetArtistIcal(ctx context.Context, artistId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetArtistIcalRequest(c.Server, artistId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEventByUrl(ctx context.Context, params *GetEventByUrlParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEventByUrlRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BatchParseEventsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBatchParseEventsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BatchParseEvents(ctx context.Context, body BatchParseEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBatchParseEventsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ParseEventWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParseEventRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ParseEvent(ctx context.Context, body ParseEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParseEventRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEventById(ctx context.Context, eventId string, params *GetEventByIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEventByIdRequest(c.Server, eventId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEventIcal(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEventIcalRequest(c.Server, eventId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetArtistByIdRequest generates requests for GetArtistById
func NewGetArtistByIdRequest(server string, artistId string, params *GetArtistByIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "artistId", runtime.ParamLocationPath, artistId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/artists/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Refresh != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "refresh", runtime.ParamLocationQuery, *params.Refresh); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetArtistIcalRequest generates requests for GetArtistIcal
func NewGetArtistIcalRequest(server string, artistId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "artistId", runtime.ParamLocationPath, artistId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/artists/%s/ical", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEventByUrlRequest generates requests for GetEventByUrl
func NewGetEventByUrlRequest(server string, params *GetEventByUrlParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "url", runtime.ParamLocationQuery, params.Url); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Refresh != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "refresh", runtime.ParamLocationQuery, *params.Refresh); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBatchParseEventsRequest calls the generic BatchParseEvents builder with application/json body
func NewBatchParseEventsRequest(server string, body BatchParseEventsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBatchParseEventsRequestWithBody(server, "application/json", bodyReader)
}

// NewBatchParseEventsRequestWithBody generates requests for BatchParseEvents with any type of body
func NewBatchParseEventsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events/batch")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewParseEventRequest calls the generic ParseEvent builder with application/json body
func NewParseEventRequest(server string, body ParseEventJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewParseEventRequestWithBody(server, "application/json", bodyReader)
}

// NewParseEventRequestWithBody generates requests for ParseEvent with any type of body
func NewParseEventRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events/parse")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetEventByIdRequest generates requests for GetEventById
func NewGetEventByIdRequest(server string, eventId string, params *GetEventByIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "eventId", runtime.ParamLocationPath, eventId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Refresh != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "refresh", runtime.ParamLocationQuery, *params.Refresh); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEventIcalRequest generates requests for GetEventIcal
func NewGetEventIcalRequest(server string, eventId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "eventId", runtime.ParamLocationPath, eventId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events/%s/ical", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetArtistByIdWithResponse request
	GetArtistByIdWithResponse(ctx context.Context, artistId string, params *GetArtistByIdParams, reqEditors ...RequestEditorFn) (*GetArtistByIdResponse, error)

	// GetArtistIcalWithResponse request
	GetArtistIcalWithResponse(ctx context.Context, artistId string, reqEditors ...RequestEditorFn) (*GetArtistIcalResponse, error)

	// GetEventByUrlWithResponse request
	GetEventByUrlWithResponse(ctx context.Context, params *GetEventByUrlParams, reqEditors ...RequestEditorFn) (*GetEventByUrlResponse, error)

	// BatchParseEventsWithBodyWithResponse request with any body
	BatchParseEventsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BatchParseEventsResponse, error)

	BatchParseEventsWithResponse(ctx context.Context, body BatchParseEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*BatchParseEventsResponse, error)

	// ParseEventWithBodyWithResponse request with any body
	ParseEventWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ParseEventResponse, error)

	ParseEventWithResponse(ctx context.Context, body ParseEventJSONRequestBody, reqEditors ...RequestEditorFn) (*ParseEventResponse, error)

	// GetEventByIdWithResponse request
	GetEventByIdWithResponse(ctx context.Context, eventId string, params *GetEventByIdParams, reqEditors ...RequestEditorFn) (*GetEventByIdResponse, error)

	// GetEventIcalWithResponse request
	GetEventIcalWithResponse(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*GetEventIcalResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)
}

type GetArtistByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ArtistDetailResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetArtistByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetArtistByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetArtistIcalResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetArtistIcalResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetArtistIcalResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEventByUrlResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetEventByUrlResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEventByUrlResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BatchParseEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BatchEventResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r BatchParseEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BatchParseEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ParseEventResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ParseEventResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ParseEventResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEventByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetEventByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEventByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEventIcalResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetEventIcalResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEventIcalResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetArtistByIdWithResponse request returning *GetArtistByIdResponse
func (c *ClientWithResponses) GetArtistByIdWithResponse(ctx context.Context, artistId string, params *GetArtistByIdParams, reqEditors ...RequestEditorFn) (*GetArtistByIdResponse, error) {
	rsp, err := c.GetArtistById(ctx, artistId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetArtistByIdResponse(rsp)
}

// GetArtistIcalWithResponse request returning *GetArtistIcalResponse
func (c *ClientWithResponses) GetArtistIcalWithResponse(ctx context.Context, artistId string, reqEditors ...RequestEditorFn) (*GetArtistIcalResponse, error) {
	rsp, err := c.GetArtistIcal(ctx, artistId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetArtistIcalResponse(rsp)
}

// GetEventByUrlWithResponse request returning *GetEventByUrlResponse
func (c *ClientWithResponses) GetEventByUrlWithResponse(ctx context.Context, params *GetEventByUrlParams, reqEditors ...RequestEditorFn) (*GetEventByUrlResponse, error) {
	rsp, err := c.GetEventByUrl(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEventByUrlResponse(rsp)
}

// BatchParseEventsWithBodyWithResponse request with arbitrary body returning *BatchParseEventsResponse
func (c *ClientWithResponses) BatchParseEventsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BatchParseEventsResponse, error) {
	rsp, err := c.BatchParseEventsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBatchParseEventsResponse(rsp)
}

func (c *ClientWithResponses) BatchParseEventsWithResponse(ctx context.Context, body BatchParseEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*BatchParseEventsResponse, error) {
	rsp, err := c.BatchParseEvents(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBatchParseEventsResponse(rsp)
}

// ParseEventWithBodyWithResponse request with arbitrary body returning *ParseEventResponse
func (c *ClientWithResponses) ParseEventWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ParseEventResponse, error) {
	rsp, err := c.ParseEventWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParseEventResponse(rsp)
}

func (c *ClientWithResponses) ParseEventWithResponse(ctx context.Context, body ParseEventJSONRequestBody, reqEditors ...RequestEditorFn) (*ParseEventResponse, error) {
	rsp, err := c.ParseEvent(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParseEventResponse(rsp)
}

// GetEventByIdWithResponse request returning *GetEventByIdResponse
func (c *ClientWithResponses) GetEventByIdWithResponse(ctx context.Context, eventId string, params *GetEventByIdParams, reqEditors ...RequestEditorFn) (*GetEventByIdResponse, error) {
	rsp, err := c.GetEventById(ctx, eventId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEventByIdResponse(rsp)
}

// GetEventIcalWithResponse request returning *GetEventIcalResponse
func (c *ClientWithResponses) GetEventIcalWithResponse(ctx context.Context, eventId string, reqEditors ...RequestEditorFn) (*GetEventIcalResponse, error) {
	rsp, err := c.GetEventIcal(ctx, eventId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEventIcalResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ParseGetArtistByIdResponse parses an HTTP response from a GetArtistByIdWithResponse call
func ParseGetArtistByIdResponse(rsp *http.Response) (*GetArtistByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetArtistByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ArtistDetailResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetArtistIcalResponse parses an HTTP response from a GetArtistIcalWithResponse call
func ParseGetArtistIcalResponse(rsp *http.Response) (*GetArtistIcalResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetArtistIcalResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetEventByUrlResponse parses an HTTP response from a GetEventByUrlWithResponse call
func ParseGetEventByUrlResponse(rsp *http.Response) (*GetEventByUrlResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEventByUrlResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseBatchParseEventsResponse parses an HTTP response from a BatchParseEventsWithResponse call
func ParseBatchParseEventsResponse(rsp *http.Response) (*BatchParseEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BatchParseEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BatchEventResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseParseEventResponse parses an HTTP response from a ParseEventWithResponse call
func ParseParseEventResponse(rsp *http.Response) (*ParseEventResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ParseEventResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetEventByIdResponse parses an HTTP response from a GetEventByIdWithResponse call
func ParseGetEventByIdResponse(rsp *http.Response) (*GetEventByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEventByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetEventIcalResponse parses an HTTP response from a GetEventIcalWithResponse call
func ParseGetEventIcalResponse(rsp *http.Response) (*GetEventIcalResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEventIcalResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Artist Profile and Events
	// (GET /api/v1/artists/{artistId})
	GetArtistById(w http.ResponseWriter, r *http.Request, artistId string, params GetArtistByIdParams)
	// Get Artist iCalendar Feed
	// (GET /api/v1/artists/{artistId}/ical)
	GetArtistIcal(w http.ResponseWriter, r *http.Request, artistId string)
	// Get Event by URL Query
	// (GET /api/v1/events)
	GetEventByUrl(w http.ResponseWriter, r *http.Request, params GetEventByUrlParams)
	// Batch Parse Events
	// (POST /api/v1/events/batch)
	BatchParseEvents(w http.ResponseWriter, r *http.Request)
	// Parse Event
	// (POST /api/v1/events/parse)
	ParseEvent(w http.ResponseWriter, r *http.Request)
	// Get Event by ID
	// (GET /api/v1/events/{eventId})
	GetEventById(w http.ResponseWriter, r *http.Request, eventId string, params GetEventByIdParams)
	// Get Event iCalendar Feed
	// (GET /api/v1/events/{eventId}/ical)
	GetEventIcal(w http.ResponseWriter, r *http.Request, eventId string)
	// Health Check
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetArtistById operation middleware
func (siw *ServerInterfaceWrapper) GetArtistById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId string

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", r.PathValue("artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArtistByIdParams

	// ------------- Optional query parameter "refresh" -------------

	err = runtime.BindQueryParameter("form", true, false, "refresh", r.URL.Query(), &params.Refresh)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refresh", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtistById(w, r, artistId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArtistIcal operation middleware
func (siw *ServerInterfaceWrapper) GetArtistIcal(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId string

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", r.PathValue("artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtistIcal(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventByUrl operation middleware
func (siw *ServerInterfaceWrapper) GetEventByUrl(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventByUrlParams

	// ------------- Required query parameter "url" -------------

	if paramValue := r.URL.Query().Get("url"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "url"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "url", r.URL.Query(), &params.Url)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "url", Err: err})
		return
	}

	// ------------- Optional query parameter "refresh" -------------

	err = runtime.BindQueryParameter("form", true, false, "refresh", r.URL.Query(), &params.Refresh)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refresh", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventByUrl(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BatchParseEvents operation middleware
func (siw *ServerInterfaceWrapper) BatchParseEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BatchParseEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ParseEvent operation middleware
func (siw *ServerInterfaceWrapper) ParseEvent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ParseEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventById operation middleware
func (siw *ServerInterfaceWrapper) GetEventById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId string

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventByIdParams

	// ------------- Optional query parameter "refresh" -------------

	err = runtime.BindQueryParameter("form", true, false, "refresh", r.URL.Query(), &params.Refresh)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refresh", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventById(w, r, eventId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventIcal operation middleware
func (siw *ServerInterfaceWrapper) GetEventIcal(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "eventId" -------------
	var eventId string

	err = runtime.BindStyledParameterWithOptions("simple", "eventId", r.PathValue("eventId"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventIcal(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/artists/{artistId}", wrapper.GetArtistById)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/artists/{artistId}/ical", wrapper.GetArtistIcal)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/events", wrapper.GetEventByUrl)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/events/batch", wrapper.BatchParseEvents)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/events/parse", wrapper.ParseEvent)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/events/{eventId}", wrapper.GetEventById)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/events/{eventId}/ical", wrapper.GetEventIcal)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)

	return m
}
